# Problem Statement 1

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [29]:
# if N is not specified it returns square array
# if N is empty it returns the length of N
# if increasing =True then Order of the powers of the columns
# increase from left to right.
# if False(default) then they are reversed.

import numpy as np

def vandermonde(arr, N = None, increasing = False):
    temp_list = []
    
    if N is None:
        N = len(arr)
    
    if increasing == False:
        for x in arr:
            for i in range(N):
                temp_list.append(x ** (N - 1 - i))
    else:
        for x in arr:
            for i in range(N):
                temp_list.append(x ** i)
                
                
    temp_arr = np.array(temp_list)
    new_arr = temp_arr.reshape(arr.size, N)
    return new_arr


x=np.array([1,2,4,5])
y=vandermonde(x,3)
print(y)

[[ 1  1  1]
 [ 4  2  1]
 [16  4  1]
 [25  5  1]]


# Problem Statement 2

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

In [ ]:
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

## Question:


Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [33]:
import numpy as np

def mov_avg_win(arr, window_size):
    n = len(arr)
    no_possib = n - window_size + 1
    avgs = []
    for i in range(len(arr)):
        if len(avgs) < no_possib:
            sums=np.sum(arr[i:i+window_size])/window_size
            avgs.append((round(sums,2)))
    return avgs
                
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(mov_avg_win(arr, 3))
                        
            

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
